ckeditor/ckeditor5-widget

- src/utils.js
- tests/utils.js
Fix: Added initial `contenteditable` state for editable widget. Closes #9.
> Added initial contenteditable state for editable widget.

- src/highlightstack.js
- src/utils.js
- tests/highlightstack.js
- tests/utils.js
Other: HighlightDescriptor can contain an array of CSS classes. Closes #1092.
> Array of CSS classes can be passed in HighlightDescriptor.

- src/widget.js
- tests/widget.js
Feature: Ctrl+A in a nested editable should select nested editable's content. Closes #13.
---
Also closes https://github.com/ckeditor/ckeditor5-image/issues/55.
> t/13: Ctrl+A in a nested editable should select nested editable's content

- src/widget.js
- tests/widget.js
Fix: Nested element structures next to widgets will be correctly removed when pressing <kbd>Backspace</kbd> or <kbd>Delete</kbd>. Closes #19.
---
Bug reported in https://github.com/ckeditor/ckeditor5/issues/532 cannot be reproduced anymore with this fix.
> T/19: Remove the entire empty element if it is next to a widget

- src/widget.js
- tests/widget.js
Fix: <kbd>Backspace</kbd> and <kbd>Delete</kbd> actions were not disabled when read only mode was enabled. Closes #6.
> T/6: Prevents from deleting widget when the read only mode is enabled

- src/highlightstack.js
- src/utils.js
- tests/highlightstack.js
- tests/utils.js
Other: Widgets highlight remove handler will now use only descriptor id, instead of the full descriptor.
BREAKING CHANGE: `HighlightStack.remove` method uses highlight id instead of `HighlightDescriptor`.
> Changed how removeHighlight is handled according do changes in engine.

- src/widget.js
- tests/widget.js
- theme/theme.scss
Fix: Correctly handling select all keystroke when widget is selected. Closes #23.
> Handling ctrl+a when widget is selected.

- src/utils.js
- tests/utils.js
Fix: Using strings instead of boolean values in contenteditable attribute. Closes #26.
> Fixed setting contenteditable attribute to string instead of boolean.

- package.json
- src/widget.js
- tests/widget.js
Other: Handling deletion around widgets is using `delete` event instead of listening directly on key events. Closes #29.
> Using `delete` event with widgets instead of key handling

- src/utils.js
- tests/utils.js
Fix: Replaced nested editable's `.ck-editable` class with `.ck-editor__editable` + `.ck-editor__nested-editable` to stop Grammarly throwing errors. Closes ckeditor/ckeditor5#578.
BREAKING CHANGE: The `.ck-editable` class is no longer available. Use the `.ck-editor__nested-editable` class instead.
---
Other PRs:
1. https://github.com/ckeditor/ckeditor5/pull/917 (Docs + mgit.json)
2. https://github.com/ckeditor/ckeditor5-image/pull/193
3. https://github.com/ckeditor/ckeditor5-theme-lark/pull/163
> Fix: Replaced nested editable's `.ck-editable` class with `.ck-editor__editable` + `.ck-editor__nested-editable` to stop Grammarly throwing errors.

- src/utils.js
- tests/utils.js
- tests/widget.js
Internal: `.ck` class should not be added to elements inside editor editable.
---
Part of https://github.com/ckeditor/ckeditor5/issues/936
> .ck class should not be added to elements inside editor editable

- src/widget.js
- tests/widget.js
Feature: Creating a paragraph next to the selected widget is possible using the (<kbd>Shift</kbd>+)<kbd>Enter</kbd> key (see ckeditor/ckeditor5#407).
> t/ckeditor5/407: Creating a paragraph next to the selected widget is possible using the (Shift+)Enter key

- src/utils.js
- tests/utils.js
Other: Don't set contenteditable property for widgets on Edge.
---
* Probably needs https://github.com/ckeditor/ckeditor5-engine/pull/1450 to be closed before.
* I've created also `env.isEdge`: https://github.com/ckeditor/ckeditor5-utils/pull/248.
* All (2) branches are set up in ckeditor5 repo: https://github.com/ckeditor/ckeditor5/tree/t/1079.
> Other: Don't set contenteditable property for widgets on Edge.

- src/utils.js
- tests/utils.js
Feature: Introduce `findOptimalInsertionPostion()` utility method.
---
* part of: https://github.com/ckeditor/ckeditor5-engine/pull/1545
> Unify widget insertion

- src/utils.js
- src/widget.js
- tests/manual/nested-widgets.html
- tests/manual/nested-widgets.js
- tests/manual/nested-widgets.md
- tests/utils.js
- tests/widget.js
Fix: Selection converter will mark nested widgets properly. Closes #57.
> Mark nested widgets properly

- src/widget.js
- tests/widget.js
Fix: Make widget in editable clickable. Closes ckeditor/ckeditor5-table#98.
---
* Required for table PR: https://github.com/ckeditor/ckeditor5-table/pull/155.
* Requires fixes from engine: https://github.com/ckeditor/ckeditor5-engine/pull/1608.
> T/ckeditor5 table/99: Widget in editable should be clickable

- src/widgettoolbarrepository.js
- tests/widgettoolbarrepository.js
Fix: Ensured only the widget toolbar attached to the view element which is deepest in the view tree will show up. Code and documentation refactoring in the `WidgetToolbarRepository`. Closes #60.
BREAKING CHANGE: The `visibleWhen()` function, a property of an object passed into `WidgetToolbarRepository.register()`, has been renamed to `getRelatedElement()` and must return an editing `View` element the toolbar should be attached to (instead of `Boolean`).
---
CI: https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-widget/60
Requires:
* https://github.com/ckeditor/ckeditor5-image/pull/269
* https://github.com/ckeditor/ckeditor5-table/pull/159
* https://github.com/ckeditor/ckeditor5-media-embed/pull/72
> t/60: Ensured only the widget toolbar attached to the view element which is deepest in the view tree will show up

- src/utils.js
- tests/utils.js
- tests/widget.js
- theme/widget.css
Other: Renamed the `.ck-widget_selectable` class to `.ck-widget_with-selection-handler` for better semantics. Closes #66.
BREAKING CHANGE: The `.ck-widget_selectable` class has been renamed to `.ck-widget_with-selection-handler` for better semantics.
---
Requires: 
* https://github.com/ckeditor/ckeditor5-theme-lark/pull/215
* https://github.com/ckeditor/ckeditor5-table/pull/165
> t/66: Renamed .ck-widget_selectable to .ck-widget_with-selection-handler.

- src/utils.js
- tests/widgettoolbarrepository.js
Internal: Got rid of the Symbols used to recognize view elements; replaced with strings (see ckeditor/ckeditor5#1520).
---
Part of https://github.com/ckeditor/ckeditor5/pull/1532 constellation.
> t/ckeditor5/1520b: Got rid of the Symbols used to recognize view elements; replaced with strings

- src/utils.js
- tests/manual/inline-widget.html
- tests/manual/inline-widget.js
- tests/manual/inline-widget.md
- tests/utils.js
Other: Introduce inline widget sample. Closes ckeditor/ckeditor5#1096.
---
* :tada: inline widgets
* all required changes gathered under the [ckeditor5#t/1096 branch](https://github.com/ckeditor/ckeditor5/tree/t/1096):
* engine: [PR](https://github.com/ckeditor/ckeditor5-engine/pull/1654)
* enter: [PR](https://github.com/ckeditor/ckeditor5-enter/pull/60)
* typing: [PR](https://github.com/ckeditor/ckeditor5-typing/pull/179)
ps.: WIP as other PRs requires tests
> PR: Acknowledge inline widgets

- src/widget.js
- tests/widget.js
Fix: Editor crashes after enter key on an image that is inside a blockquote. Closes ckeditor/ckeditor5#1555.
---
* This PR handles properly (as described in comment before if) enter key on object elements. The previous fix introduced problem with objects inside elements that were not described as `limit` in schema (`<blockquote>` is nether `block` nor `limit` nor anything else). The comment wasn't inline with the code as code checked is the element is not an `limit` rather then if it is a `block` (a block can be an object thus a limit).
* The better would be just to ignore `inline` elements in that handler as they should be treated as text - so the inline object should be removed by that handler.
* Also I found the superfluous check for delete key check in detecting direction of an arrow …
> T/ckeditor5/1555: Properly handle enter key on objects.

- src/widget.js
- tests/widget-integration.js
- tests/widget.js
Fix: Fixed a weird selection behavior on at least triple click. Triple click inside the nested editable will select the entire element now. Closes ckeditor/ckeditor5#1463.
---
Requires: https://github.com/ckeditor/ckeditor5-utils/pull/278.
> Fixed an issue with triple click in nested editable.

- tests/manual/inline-widget.html
Tests: Improve caret between inline widget rendering in manual tests. Closes ckeditor/ckeditor5#1571.
---
* The new bug found: https://github.com/ckeditor/ckeditor5/issues/1607
> Improve caret between inline widget rendering in manual tests.

- package.json
- src/widgettoolbarrepository.js
- tests/widgettoolbarrepository.js
Fix: Improved balloon positioning when there is more than one stack in the rotator. Closes #92.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
> Improved balloon positioning when there is more than one stack in the rotator

- tests/manual/selection-handler.html
- tests/manual/selection-handler.js
- tests/manual/selection-handler.md
Tests: Added a manual test for widget selection handler in different UI language directions. See ckeditor/ckeditor5#1151.
---
A piece of https://github.com/ckeditor/ckeditor5/pull/1881.
> t/ckeditor5/1151: Added a manual test for widget selection handler in different UI language directions

- src/widgettoolbarrepository.js
Fix: Reposition visible toolbar when it is in a not visible stack of rotator. Closes ckeditor/ckeditor5#1957.
---
* The previous fix was causing problems in some edge cases - ie when toolbar was removed on focus lost and the whole logic was re-applied twice instead of just repositioning the toolbar. See https://github.com/ckeditor/ckeditor5/issues/1957.
> Reposition visible toolbar when it is in a not visible stack of rotator.

- src/widget.js
- tests/manual/keyboard.html
- tests/manual/keyboard.js
- tests/manual/keyboard.md
- tests/widget.js
Fix: Keyboard navigation should work around widgets in RTL content. Closes #97.
> t/97: Fix: Improved keyboard navigation around widgets in RTL content.

- src/widgetresize/resizer.js
- src/widgetresize/resizerstate.js
Fix: Initial resize of a side image with no width predefined now gives correct percentage values.
---
Related issue ckeditor/ckeditor5-image#306.
> Fixed resizer initial percentage values for side images

- src/widgettoolbarrepository.js
- tests/widgettoolbarrepository.js
Feature: Introduced API to disable the [`WidgetToolbarRepository`](https://ckeditor.com/docs/ckeditor5/16.0.0/api/module_widget_widgettoolbarrepository-WidgetToolbarRepository.html) plugin. Closes ckeditor/ckeditor5#5964.
---
Since this is already used in the `Command` class, there was an option to implement this as an interface and add a common mixin to avoid code duplication. However during an offline meeting we decided to go with easier option and just copy'n'paste it from the `Command` class.
> Introduced disabling API for the WidgetToolbarRepository class

- src/widgetresize.js
- src/widgetresize/resizer.js
Fix: Fixed image resize behavior upon short clicking a handle without dragging. Image will no longer became full width, nor will it briefly flash an unexpected size. Closes ckeditor/ckeditor5#5189 and closes ckeditor/ckeditor5#5195.
MINOR BREAKING CHANGE: Resizer options object now also takes an editor instance.
---
* **note** Since [ResizerOptions](https://ckeditor.com/docs/ckeditor5/latest/api/module_widget_widgetresize-ResizerOptions.html) now holds editor reference, it is no longer needed to keep [`downcastWriter`](https://ckeditor.com/docs/ckeditor5/latest/api/module_widget_widgetresize-ResizerOptions.html#member-downcastWriter) so I'd also like to remove this property. I find it to be a minor breaking change, please confirm that.
Short overview of the problems:
* flickering image at …
> Fixed image resize flashing unexpected size

- src/widgettoolbarrepository.js
Fix: Remove forceDisabled and clearForceDisabled methods from WidgetToolbarRepository, because now it inherits them from the Plugin class. Closes ckeditor/ckeditor5#5862.
---
Depends on: https://github.com/ckeditor/ckeditor5-core/pull/208
Master PR: https://github.com/ckeditor/ckeditor5-typing/pull/222
> i/5862: Remove forceDisabled and clearForceDisabled methods from WidgetToolbarRepository

- tests/widget-integration.js
Tests: Fixed tests failing due to invalid widget selection. Closes ckeditor/ckeditor5#6226.
---
Note, the resizer tests are fixed by #115.
> Fixed tests failing due to invalid widget selection

- src/widget.js
- tests/widget.js
Other: Moved the <kbd>Ctrl</kbd>+<kbd>A</kbd> keystroke handling in widgets to the [`SelectAll`](https://ckeditor.com/docs/ckeditor5/latest/api/module_select-all_selectall-SelectAll.html) plugin (see ckeditor/ckeditor5#6536).
MINOR BREAKING CHANGE: Make sure the latest version of the [`Essentials`](https://ckeditor.com/docs/ckeditor5/latest/api/essentials.html) plugin or the [`SelectAll`](https://ckeditor.com/docs/ckeditor5/latest/api/module_select-all_selectall-SelectAll.html) plugin is installed in your integration. Either is required for proper keystroke handling in editor widgets.
---
**Requires https://github.com/ckeditor/ckeditor5-select-all/pull/1.**
> i/6536: Moved the Ctrl+A handling to the Select all plugin
