LICENSE.md
README.md
package.json
src/utils.js
src/widget.js
src/widgetengine.js
tests/.jshintrc
tests/utils.js
tests/widget.js
tests/widgetengine.js
theme/theme.scss

Feature: Moved widget API from image feature. Closes #1.

Moved Widget API from image feature

---

src/utils.js
tests/utils.js

Other: Adjusted widget to the editor read-only mode. Closes #7.

Adjusted widget to the editor read-only mode.

---

src/utils.js
src/virtualselectionstack.js
tests/utils.js
tests/virtualselectionstack.js

Feature: Virtual selection support for widgets. Closes #11.
---
Please close together with: https://github.com/ckeditor/ckeditor5-engine/pull/1040.

Virtual selection support

---

src/highlightstack.js
src/utils.js
tests/highlightstack.js
tests/utils.js

Internal: Renamed virtual selection to highlight.

T/ckeditor5 engine/1085

---

src/highlightstack.js
tests/highlightstack.js
tests/utils.js

Internal: Use `id` property of HighlightDescriptor.

t/ckeditor5 engine/1102

---

src/highlightstack.js

Docs: Fixed docs after update in `ckeditor5-engine`.
---
Merge if docs changes in https://github.com/ckeditor/ckeditor5-engine/pull/1109 are merged too.

Docs: changed docs to fit changes in engine.

---

src/widget.js

Internal: Update API usage after merge t/1258 on engine.

Aligned code to introduced `Schema#getNearesetSelectionRange`.

---

tests/widget.js

Other: Aligning with new conversion helpers API.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

Other: Aligning with new conversion helpers API

---

src/widget.js

Other: Aligned to changes in ckeditor5-engine.
---
Related to https://github.com/ckeditor/ckeditor5-engine/pull/1314

Aligned to changes in ckeditor5-engine

---

docs/api/widget.md

Other: Align feature class naming to a new scheme.
---
* Part of feature split: https://github.com/ckeditor/ckeditor5/issues/488

Align feature class naming to a new scheme.

---

src/widget.js

Intenal: Unnecessarily nested `model.change()` blocks. Closes #35.

Removed nested "model.change()" blocks

---

tests/widget.js

Internal: Align code to the API changes (selection post-fixer).
---
* Part of engine PR: https://github.com/ckeditor/ckeditor5-engine/pull/1450

Internal: Align code to the API changes (selection post-fixer).

---

tests/widget.js

Tests: Fix tests for widget in Edge.
---
* I've broke the CI... sorry :crying_cat_face:

Tests: Fix tests for widget in Edge.

---

tests/utils.js
tests/widget.js

Tests: Properly use sinon sandbox in tests.
---
* Fixing  as in related PR: https://github.com/ckeditor/ckeditor5-image/pull/222
* Should fix broken CI

Tests: Properly use sinon sandbox in tests.

---

tests/utils.js

Internal: Adjusted code to `Writer` to `DowncastWriter` rename in `ckeditor5-engine`.
---
See https://github.com/ckeditor/ckeditor5-engine/issues/1515.

Adjusted code to 'Writer' to 'DowncastWriter' rename in 'ckeditor5-engine'

---

src/widgettoolbarrepository.js
tests/widgettoolbarrepository.js

Other: Align code to the latest changes in editor.plugin API.
---
* Part of: https://github.com/ckeditor/ckeditor5-core/pull/152

Align code to the latest changes in editor.plugin API.

---

tests/widgettoolbarrepository.js

Tests: Aligned tests to the new editing view behavior (see ckeditor/ckeditor5#479).
---
Part of the [constellation](https://github.com/ckeditor/ckeditor5/tree/t/479).

t/ckeditor5/479: Aligned tests to the new editing view behavior

---

src/widgettoolbarrepository.js
tests/widgettoolbarrepository.js

Internal: Aligned code to the latest `ContextualBalloon` API. Part of https://github.com/ckeditor/ckeditor5-ui/issues/491.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

Aligned code with rotatable contextual balloon.

---

src/widgettoolbarrepository.js
tests/widgettoolbarrepository.js

Internal: Aligned code to introduced error context. Required by ckeditor/ckeditor5-watchdog#2.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

Align code to introduced error context

---

src/widgetresize/resizerstate.js

Docs: Added missing API docs for the image resizer state. Closes ckeditor/ckeditor5-image#324.

Added missing API docs for the image resizer state

---

tests/widgetresize.js
tests/widgetresize/resizer.js

Tests: Widget package reports 100% CC when run alone. Closes ckeditor/ckeditor5#6352.

Widget package reports 100% CC when run alone

---

theme/widgetresize.css

Internal: Fixed stylelint errors related to colors and indentation (see ckeditor/ckeditor5-dev#611).

ckeditor5-dev/i/611: Fixed stylelint errors related to colors and indentation
